# https://www.10xgenomics.com/support/software/xenium-panel-designer/latest/tutorials/create-gene-list#yesprobe
xenium_v1_gene_list = "https://cdn.10xgenomics.com/raw/upload/v1721161837/software-support/Xenium-panels/human_and_mouse_2020-A-ref-yesprobe-genes_v1assay.csv"

xenium_prime_gene_list = "https://cdn.10xgenomics.com/raw/upload/v1721161425/software-support/Xenium-panels/human_and_mouse_genes_xenium_prime-yesprobe-genes.csv"
